import express from "express";
import {
	generateAutoPlan,
	getCurrentAutoPlan,
	adjustAutoPlan,
	triggerProgression,
	deactivateAutoPlan,
	getAutoPlanById,
} from "../controllers/autoGeneratedPlan.controllers.js";
import { verifyToken } from "../middlewares/verifyToken.middleware.js";

const router = express.Router();

router.post("/generate", verifyToken, generateAutoPlan);
router.get("/current", verifyToken, getCurrentAutoPlan);
router.get("/:id", verifyToken, getAutoPlanById);
router.put("/:id/adjust", verifyToken, adjustAutoPlan);
router.post("/:id/progress", verifyToken, triggerProgression);
router.delete("/:id", verifyToken, deactivateAutoPlan);

export default router;
