import colors from "colors";
import express from "express";
import dotenv from "dotenv";
import connectDB from "./config/db.js";
import authRoutes from "./routes/auth.routes.js";
import cookieParser from "cookie-parser";
import cors from "cors";
import exerciseRoutes from "./routes/exercise.routes.js";
import profileRoutes from "./routes/profile.routes.js";
import planTemplateRoutes from "./routes/planTemplate.routes.js";
import userPlanRoutes from "./routes/userPlan.routes.js";
import dailySessionRoutes from "./routes/dailySession.routes.js";
import sessionLogRoutes from "./routes/sessionLog.routes.js";
import dietRoutes from "./routes/diet.routes.js";
import autoGeneratedPlanRoutes from "./routes/autoGeneratedPlan.routes.js";
import streakRoutes from "./routes/streak.routes.js";

// config
dotenv.config();
connectDB();

const app = express();

const frontendUrl = process.env.FRONTEND_URL;

// middleware
app.use(express.json());
app.use(cookieParser());
app.use(cors({ origin: frontendUrl, credentials: true }));

// routes
app.use("/api/auth", authRoutes);
app.use("/api/exercises", exerciseRoutes);
app.use("/api/profile", profileRoutes);
app.use("/api/plan-templates", planTemplateRoutes);
app.use("/api/user-plan", userPlanRoutes);
app.use("/api/daily-session", dailySessionRoutes);
app.use("/api/session", sessionLogRoutes);
app.use("/api/diet", dietRoutes);
app.use("/api/auto-plan", autoGeneratedPlanRoutes);
app.use("/api/streak", streakRoutes);

const PORT = process.env.PORT || 5017;

app.listen(PORT, () => console.log(`Server running on port ${PORT}`.blue.bold));
