import colors from "colors";
import express from "express";
import dotenv from "dotenv";
import cookieParser from "cookie-parser";
import cors from "cors";

import connectDB from "./config/db.js";

import authRoutes from "./routes/auth.routes.js";
import exerciseRoutes from "./routes/exercise.routes.js";
import profileRoutes from "./routes/profile.routes.js";
import planTemplateRoutes from "./routes/planTemplate.routes.js";
import userPlanRoutes from "./routes/userPlan.routes.js";
import dailySessionRoutes from "./routes/dailySession.routes.js";
import sessionLogRoutes from "./routes/sessionLog.routes.js";
import dietRoutes from "./routes/diet.routes.js";
import autoGeneratedPlanRoutes from "./routes/autoGeneratedPlan.routes.js";
import streakRoutes from "./routes/streak.routes.js";

// Load env
dotenv.config();

const app = express();

app.set("trust proxy", 1);

const allowedOrigins = (
	process.env.CORS_ORIGINS ||
	process.env.FRONTEND_URL ||
	""
)
	.split(",")
	.map((s) => s.trim())
	.filter(Boolean);

const corsOptions = {
	origin(origin, cb) {
		if (!origin) return cb(null, true);
		const allowed =
			allowedOrigins.length === 0 || allowedOrigins.includes(origin);
		return allowed
			? cb(null, true)
			: cb(new Error(`CORS blocked for origin: ${origin}`));
	},
	credentials: true,
	optionsSuccessStatus: 200,
};

app.use(cors(corsOptions));

app.use(express.json());
app.use(cookieParser());

app.get("/healthz", (_req, res) => res.status(200).send("ok"));
app.get("/", (_req, res) => res.status(200).json({ status: "Flexora API up" }));

app.use("/api/auth", authRoutes);
app.use("/api/exercises", exerciseRoutes);
app.use("/api/profile", profileRoutes);
app.use("/api/plan-templates", planTemplateRoutes);
app.use("/api/user-plan", userPlanRoutes);
app.use("/api/daily-session", dailySessionRoutes);
app.use("/api/session", sessionLogRoutes);
app.use("/api/diet", dietRoutes);
app.use("/api/auto-plan", autoGeneratedPlanRoutes);
app.use("/api/streak", streakRoutes);

app.use((req, res) => {
	res.status(404).json({ error: "Route not found", path: req.originalUrl });
});

app.use((err, _req, res, _next) => {
	console.error("Unhandled error:", err);
	res.status(500).json({ error: "Internal Server Error" });
});

const PORT = process.env.PORT || 5017;

async function start() {
	try {
		await connectDB();
		console.log("MongoDB connected".green.bold);
		app.listen(PORT, () => {
			console.log(`Server running on port ${PORT}`.blue.bold);
		});
	} catch (err) {
		console.error("Startup error:", err);
		process.exit(1);
	}
}

start();
