import { useEffect, useState } from "react";
import api from "../config/axios";
import { Calendar, Dumbbell, Clock, Target, ChevronDown, ChevronUp, TrendingUp, AlertCircle } from "lucide-react";
import { useAutoPlanStore } from "../store/autoPlan/autoPlanStore";

const MyPlans = () => {
	const [userPlan, setUserPlan] = useState(null);
	const [loading, setLoading] = useState(true);
	const [error, setError] = useState(null);
	const [expandedDays, setExpandedDays] = useState({});
	const [upcomingSessions, setUpcomingSessions] = useState([]);
	const [showProgression, setShowProgression] = useState(false);
	const [progressionSuggestions, setProgressionSuggestions] = useState([]);
	const [loadingProgression, setLoadingProgression] = useState(false);

	const { triggerProgression } = useAutoPlanStore();

	useEffect(() => {
		fetchUserPlan();
	}, []);

	useEffect(() => {
		if (userPlan) {
			generateUpcomingSessions();
		}
	}, [userPlan]);

	const fetchUserPlan = async () => {
		try {
			setLoading(true);
			setError(null);
			const response = await api.get("/user-plan");
			console.log("User Plan Response:", response.data);
			setUserPlan(response.data.userPlan);
		} catch (err) {
			console.error("Error fetching user plan:", err);
			if (err.response?.status === 404) {
				setError("No active plan found. Please create or assign a plan.");
			} else {
				setError(err.response?.data?.message || "Failed to fetch your plans");
			}
		} finally {
			setLoading(false);
		}
	};

	const generateUpcomingSessions = () => {
		if (!userPlan) return;

		const sessions = [];
		const today = new Date();
		today.setHours(0, 0, 0, 0);

		// Get the workout days from either template or auto-generated plan
		let workoutDays = [];
		let preferredDays = [];

		if (userPlan.templateId?.dayTemplates) {
			workoutDays = userPlan.templateId.dayTemplates;
			preferredDays = userPlan.templateId.preferredDays || [];
		} else if (userPlan.autoGeneratedPlanId?.weeklyStructure) {
			workoutDays = userPlan.autoGeneratedPlanId.weeklyStructure;
			preferredDays = userPlan.autoGeneratedPlanId.generationParams?.preferred_days || [];
		}

		if (!workoutDays.length || !preferredDays.length) return;

		// Map days of week to numbers
		const dayNameToNumber = {
			sunday: 0,
			monday: 1,
			tuesday: 2,
			wednesday: 3,
			thursday: 4,
			friday: 5,
			saturday: 6,
		};

		// Get preferred day numbers sorted
		const preferredDayNumbers = preferredDays
			.map(day => dayNameToNumber[day.toLowerCase()])
			.sort((a, b) => a - b);

		// Generate next 14 days of sessions
		for (let i = 0; i < 14; i++) {
			const date = new Date(today);
			date.setDate(date.getDate() + i);
			const dayOfWeek = date.getDay();

			// Check if this day is a workout day
			const dayIndex = preferredDayNumbers.indexOf(dayOfWeek);
			if (dayIndex !== -1 && dayIndex < workoutDays.length) {
				const workout = workoutDays[dayIndex];
				sessions.push({
					date: new Date(date),
					workout: workout,
					dayIndex: dayIndex,
					isToday: i === 0,
				});
			}
		}

		setUpcomingSessions(sessions);
	};

	const handleCheckProgression = async () => {
		if (!userPlan?.autoGeneratedPlanId?._id) return;

		try {
			setLoadingProgression(true);
			const result = await triggerProgression(userPlan.autoGeneratedPlanId._id, false);
			
			if (result.success && result.data.suggestions) {
				setProgressionSuggestions(result.data.suggestions);
			}
		} catch (error) {
			console.error("Error checking progression:", error);
		} finally {
			setLoadingProgression(false);
		}
	};

	const handleApplyProgression = async () => {
		if (!userPlan?.autoGeneratedPlanId?._id) return;

		try {
			setLoadingProgression(true);
			const result = await triggerProgression(userPlan.autoGeneratedPlanId._id, true);
			
			if (result.success) {
				// Refresh the plan
				await fetchUserPlan();
				setProgressionSuggestions([]);
				alert("Progression applied successfully!");
			}
		} catch (error) {
			console.error("Error applying progression:", error);
		} finally {
			setLoadingProgression(false);
		}
	};

	const toggleDay = (index) => {
		setExpandedDays((prev) => ({
			...prev,
			[index]: !prev[index],
		}));
	};

	const getDayOfWeekLabel = (dayOfWeek) => {
		if (!dayOfWeek) return "";
		return dayOfWeek.charAt(0).toUpperCase() + dayOfWeek.slice(1);
	};

	const renderUpcomingSessions = () => {
		if (!upcomingSessions.length) return null;

		return (
			<div className="card bg-base-100 shadow-lg">
				<div className="card-body">
					<h3 className="text-xl font-bold mb-4 flex items-center gap-2">
						<Calendar className="w-5 h-5" />
						Upcoming Sessions (Next 2 Weeks)
					</h3>

					<div className="space-y-3">
						{upcomingSessions.map((session, index) => {
							const dateStr = session.date.toLocaleDateString('en-US', { 
								weekday: 'short', 
								month: 'short', 
								day: 'numeric' 
							});
							
							return (
								<div 
									key={index} 
									className={`border rounded-lg p-4 ${
										session.isToday 
											? 'border-primary bg-primary/10' 
											: 'border-base-300'
									}`}
								>
									<div className="flex items-center justify-between mb-2">
										<div className="flex items-center gap-3">
											<div className={`badge ${session.isToday ? 'badge-primary' : 'badge-neutral'}`}>
												{dateStr}
											</div>
											{session.isToday && (
												<span className="badge badge-success badge-sm">Today</span>
											)}
										</div>
										<div className="badge badge-outline">
											{session.workout.exercises?.length || 0} exercises
										</div>
									</div>

									<h4 className="font-bold mb-2">
										{session.workout.name || `Day ${session.dayIndex + 1}`}
									</h4>
									
									{session.workout.focus && (
										<p className="text-sm text-base-content/70 mb-2 capitalize">
											Focus: {session.workout.focus.replace("_", " ")}
										</p>
									)}

									{session.workout.exercises && session.workout.exercises.length > 0 && (
										<div className="mt-3">
											<p className="text-sm font-semibold mb-2">Exercise Preview:</p>
											<div className="space-y-1">
												{session.workout.exercises.slice(0, 3).map((exercise, exIndex) => (
													<div key={exIndex} className="text-sm flex items-center gap-2">
														<Dumbbell className="w-3 h-3 text-primary" />
														<span>{exercise.exerciseId?.name || "Exercise"}</span>
														{exercise.planned && (
															<span className="text-xs text-base-content/60">
																{exercise.planned.sets && `${exercise.planned.sets} × `}
																{exercise.planned.reps && `${exercise.planned.reps} reps`}
																{exercise.planned.load_kg && ` @ ${exercise.planned.load_kg}kg`}
															</span>
														)}
													</div>
												))}
												{session.workout.exercises.length > 3 && (
													<p className="text-xs text-base-content/60 ml-5">
														+{session.workout.exercises.length - 3} more exercises
													</p>
												)}
											</div>
										</div>
									)}
								</div>
							);
						})}
					</div>
				</div>
			</div>
		);
	};

	const renderProgressionHistory = () => {
		if (!userPlan?.autoGeneratedPlanId?.progressionHistory?.length) return null;

		return (
			<div className="card bg-base-100 shadow-lg">
				<div className="card-body">
					<h3 className="text-xl font-bold mb-4 flex items-center gap-2">
						<TrendingUp className="w-5 h-5" />
						Progression History
					</h3>

					<div className="space-y-3">
						{userPlan.autoGeneratedPlanId.progressionHistory.slice(-5).reverse().map((entry, index) => (
							<div key={index} className="border border-base-300 rounded-lg p-4">
								<div className="flex items-center justify-between mb-2">
									<span className="badge badge-primary">
										{new Date(entry.date).toLocaleDateString()}
									</span>
									<span className="text-sm text-base-content/70">
										{entry.adjustments.length} adjustment{entry.adjustments.length > 1 ? 's' : ''}
									</span>
								</div>
								
								<div className="space-y-2">
									{entry.adjustments.map((adj, adjIndex) => (
										<div key={adjIndex} className="text-sm">
											<p className="font-semibold">{adj.change}</p>
											<p className="text-base-content/70">{adj.reason}</p>
										</div>
									))}
								</div>
							</div>
						))}
					</div>

					{userPlan.autoGeneratedPlanId.progressionHistory.length > 5 && (
						<button 
							className="btn btn-sm btn-ghost mt-2"
							onClick={() => setShowProgression(!showProgression)}
						>
							{showProgression ? 'Show Less' : `View All (${userPlan.autoGeneratedPlanId.progressionHistory.length})`}
						</button>
					)}
				</div>
			</div>
		);
	};

	const renderProgressionSuggestions = () => {
		if (!progressionSuggestions.length) return null;

		return (
			<div className="card bg-base-100 shadow-lg border-2 border-info">
				<div className="card-body">
					<h3 className="text-xl font-bold mb-2 flex items-center gap-2">
						<AlertCircle className="w-5 h-5 text-info" />
						Progression Suggestions Ready
					</h3>
					<p className="text-sm text-base-content/70 mb-4">
						Based on your recent performance, here are the recommended adjustments:
					</p>

					<div className="space-y-3">
						{progressionSuggestions.map((suggestion, index) => (
							<div key={index} className="border border-base-300 rounded-lg p-4 bg-base-200">
								<div className="flex items-center gap-2 mb-2">
									<span className={`badge ${suggestion.type === 'progression' ? 'badge-success' : 'badge-warning'}`}>
										{suggestion.type}
									</span>
									<span className="text-sm font-semibold">Day {suggestion.dayNumber}</span>
								</div>
								
								<p className="text-sm mb-2">{suggestion.reason}</p>
								
								<div className="grid grid-cols-2 gap-4 text-sm">
									<div>
										<p className="font-semibold mb-1">Current:</p>
										<div className="bg-base-100 p-2 rounded">
											{suggestion.currentPlanned.sets && <p>Sets: {suggestion.currentPlanned.sets}</p>}
											{suggestion.currentPlanned.reps && <p>Reps: {suggestion.currentPlanned.reps}</p>}
											{suggestion.currentPlanned.load_kg && <p>Load: {suggestion.currentPlanned.load_kg}kg</p>}
										</div>
									</div>
									<div>
										<p className="font-semibold mb-1">Suggested:</p>
										<div className="bg-success/10 p-2 rounded border border-success">
											{suggestion.suggestedPlanned.sets && <p>Sets: {suggestion.suggestedPlanned.sets}</p>}
											{suggestion.suggestedPlanned.reps && <p>Reps: {suggestion.suggestedPlanned.reps}</p>}
											{suggestion.suggestedPlanned.load_kg && <p>Load: {suggestion.suggestedPlanned.load_kg}kg</p>}
										</div>
									</div>
								</div>
							</div>
						))}
					</div>

					<div className="card-actions justify-end mt-4">
						<button 
							className="btn btn-ghost"
							onClick={() => setProgressionSuggestions([])}
						>
							Dismiss
						</button>
						<button 
							className="btn btn-success"
							onClick={handleApplyProgression}
							disabled={loadingProgression}
						>
							{loadingProgression ? (
								<span className="loading loading-spinner loading-sm"></span>
							) : (
								"Apply All"
							)}
						</button>
					</div>
				</div>
			</div>
		);
	};

	const renderWorkoutDays = () => {
		console.log("Rendering workout days. User Plan:", userPlan);
		console.log("Template dayTemplates:", userPlan?.templateId?.dayTemplates);
		console.log("Auto-generated weeklyStructure:", userPlan?.autoGeneratedPlanId?.weeklyStructure);
		
		// Check if it's a template-based plan
		if (userPlan.templateId?.dayTemplates && userPlan.templateId.dayTemplates.length > 0) {
			return (
				<div className="mt-6">
					<h3 className="text-xl font-bold mb-4 flex items-center gap-2">
						<Calendar className="w-5 h-5" />
						Workout Schedule
					</h3>

					{/* Preferred Days Display */}
					{userPlan.templateId.preferredDays && userPlan.templateId.preferredDays.length > 0 && (
						<div className="mb-4 p-3 bg-base-200 rounded-lg">
							<p className="text-sm font-semibold mb-2">Preferred Days:</p>
							<div className="flex flex-wrap gap-2">
								{userPlan.templateId.preferredDays.map((day) => (
									<span key={day} className="badge badge-primary">
										{getDayOfWeekLabel(day)}
									</span>
								))}
							</div>
						</div>
					)}

					<div className="space-y-3">
						{userPlan.templateId.dayTemplates.map((day, index) => (
							<div key={index} className="border border-base-300 rounded-lg overflow-hidden">
								<button
									onClick={() => toggleDay(index)}
									className="w-full p-4 bg-base-200 hover:bg-base-300 transition-colors flex items-center justify-between"
								>
									<div className="flex items-center gap-3">
										<div className="badge badge-lg badge-primary">
											Day {index + 1}
										</div>
										<div className="text-left">
											<h4 className="font-bold">{day.name || `Workout Day ${index + 1}`}</h4>
											{day.dayOfWeek && (
												<p className="text-sm text-base-content/70">
													{getDayOfWeekLabel(day.dayOfWeek)}
												</p>
											)}
										</div>
										<div className="badge badge-outline ml-2">
											{day.exercises?.length || 0} exercises
										</div>
									</div>
									{expandedDays[index] ? (
										<ChevronUp className="w-5 h-5" />
									) : (
										<ChevronDown className="w-5 h-5" />
									)}
								</button>

								{expandedDays[index] && day.exercises && day.exercises.length > 0 && (
									<div className="p-4 bg-base-100">
										<div className="space-y-3">
											{day.exercises.map((exercise, exIndex) => (
												<div
													key={exIndex}
													className="p-3 border border-base-300 rounded-lg hover:border-primary transition-colors"
												>
													<div className="flex items-start gap-3">
														<div className="badge badge-sm badge-secondary">
															{exIndex + 1}
														</div>
														<div className="flex-1">
															<h5 className="font-semibold flex items-center gap-2">
																<Dumbbell className="w-4 h-4" />
																{exercise.exerciseId?.name || "Exercise"}
															</h5>
															{exercise.exerciseId?.description && (
																<p className="text-sm text-base-content/70 mt-1">
																	{exercise.exerciseId.description}
																</p>
															)}
															{exercise.exerciseId?.primary_muscles && (
																<div className="flex flex-wrap gap-1 mt-2">
																	{exercise.exerciseId.primary_muscles.map((muscle, i) => (
																		<span key={i} className="badge badge-xs badge-outline">
																			{muscle}
																		</span>
																	))}
																</div>
															)}
															{exercise.planned && (
																<div className="flex flex-wrap gap-3 mt-2 text-sm">
																	{exercise.planned.sets && (
																		<span className="font-medium">
																			{exercise.planned.sets} sets
																		</span>
																	)}
																	{exercise.planned.reps && (
																		<span className="font-medium">
																			{exercise.planned.reps} reps
																		</span>
																	)}
																	{exercise.planned.load_kg && (
																		<span className="font-medium">
																			{exercise.planned.load_kg} kg
																		</span>
																	)}
																	{exercise.planned.rest_seconds && (
																		<span className="font-medium flex items-center gap-1">
																			<Clock className="w-3 h-3" />
																			{exercise.planned.rest_seconds}s rest
																		</span>
																	)}
																</div>
															)}
														</div>
													</div>
												</div>
											))}
										</div>
									</div>
								)}
							</div>
						))}
					</div>
				</div>
			);
		}

		// Check if it's an auto-generated plan
		if (userPlan.autoGeneratedPlanId?.weeklyStructure && userPlan.autoGeneratedPlanId.weeklyStructure.length > 0) {
			return (
				<div className="mt-6">
					<h3 className="text-xl font-bold mb-4 flex items-center gap-2">
						<Calendar className="w-5 h-5" />
						Weekly Workout Schedule
					</h3>

					{/* Preferred Days Display */}
					{userPlan.autoGeneratedPlanId.generationParams?.preferred_days && 
					 userPlan.autoGeneratedPlanId.generationParams.preferred_days.length > 0 && (
						<div className="mb-4 p-3 bg-base-200 rounded-lg">
							<p className="text-sm font-semibold mb-2">Preferred Days:</p>
							<div className="flex flex-wrap gap-2">
								{userPlan.autoGeneratedPlanId.generationParams.preferred_days.map((day) => (
									<span key={day} className="badge badge-primary">
										{getDayOfWeekLabel(day)}
									</span>
								))}
							</div>
						</div>
					)}

					<div className="space-y-3">
						{userPlan.autoGeneratedPlanId.weeklyStructure.map((day, index) => (
							<div key={index} className="border border-base-300 rounded-lg overflow-hidden">
								<button
									onClick={() => toggleDay(index)}
									className="w-full p-4 bg-base-200 hover:bg-base-300 transition-colors flex items-center justify-between"
								>
									<div className="flex items-center gap-3">
										<div className="badge badge-lg badge-primary">
											Day {day.dayNumber}
										</div>
										<div className="text-left">
											<h4 className="font-bold">{day.name || `Workout Day ${day.dayNumber}`}</h4>
											{day.dayOfWeek && (
												<p className="text-sm text-base-content/70">
													{getDayOfWeekLabel(day.dayOfWeek)}
												</p>
											)}
											{day.focus && (
												<p className="text-xs text-base-content/60 capitalize">
													Focus: {day.focus.replace("_", " ")}
												</p>
											)}
										</div>
										<div className="badge badge-outline ml-2">
											{day.exercises?.length || 0} exercises
										</div>
									</div>
									{expandedDays[index] ? (
										<ChevronUp className="w-5 h-5" />
									) : (
										<ChevronDown className="w-5 h-5" />
									)}
								</button>

								{expandedDays[index] && day.exercises && day.exercises.length > 0 && (
									<div className="p-4 bg-base-100">
										<div className="space-y-3">
											{day.exercises.map((exercise, exIndex) => (
												<div
													key={exIndex}
													className="p-3 border border-base-300 rounded-lg hover:border-primary transition-colors"
												>
													<div className="flex items-start gap-3">
														<div className="badge badge-sm badge-secondary">
															{exIndex + 1}
														</div>
														<div className="flex-1">
															<h5 className="font-semibold flex items-center gap-2">
																<Dumbbell className="w-4 h-4" />
																{exercise.exerciseId?.name || "Exercise"}
															</h5>
															{exercise.exerciseId?.description && (
																<p className="text-sm text-base-content/70 mt-1">
																	{exercise.exerciseId.description}
																</p>
															)}
															{exercise.exerciseId?.primary_muscles && (
																<div className="flex flex-wrap gap-1 mt-2">
																	{exercise.exerciseId.primary_muscles.map((muscle, i) => (
																		<span key={i} className="badge badge-xs badge-outline">
																			{muscle}
																		</span>
																	))}
																</div>
															)}
															{exercise.planned && (
																<div className="flex flex-wrap gap-3 mt-2 text-sm">
																	{exercise.planned.sets && (
																		<span className="font-medium">
																			{exercise.planned.sets} sets
																		</span>
																	)}
																	{exercise.planned.reps && (
																		<span className="font-medium">
																			{exercise.planned.reps} reps
																		</span>
																	)}
																	{exercise.planned.load_kg && (
																		<span className="font-medium">
																			{exercise.planned.load_kg} kg
																		</span>
																	)}
																	{exercise.planned.rest_seconds && (
																		<span className="font-medium flex items-center gap-1">
																			<Clock className="w-3 h-3" />
																			{exercise.planned.rest_seconds}s rest
																		</span>
																	)}
																</div>
															)}
														</div>
													</div>
												</div>
											))}
										</div>
									</div>
								)}
							</div>
						))}
					</div>
				</div>
			);
		}

		return null;
	};

	return (
		<div className="max-w-7xl mx-auto">
			<h1 className="text-3xl font-bold mb-6">My Plans</h1>

			{loading ? (
				<div className="card bg-base-100 shadow-lg p-6">
					<div className="flex justify-center items-center py-8">
						<span className="loading loading-spinner loading-lg"></span>
					</div>
				</div>
			) : error ? (
				<div className="alert alert-warning shadow-lg">
					<svg
						xmlns="http://www.w3.org/2000/svg"
						className="stroke-current shrink-0 h-6 w-6"
						fill="none"
						viewBox="0 0 24 24"
					>
						<path
							strokeLinecap="round"
							strokeLinejoin="round"
							strokeWidth="2"
							d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"
						/>
					</svg>
					<span>{error}</span>
				</div>
			) : userPlan ? (
				<div className="space-y-6">
					{/* Progression Suggestions - Show First if Available */}
					{renderProgressionSuggestions()}

					{/* Upcoming Sessions - Show First */}
					{renderUpcomingSessions()}

					{/* Plan Overview Card */}
					<div className="card bg-base-100 shadow-lg">
						<div className="card-body">
							<h2 className="card-title text-2xl">
								{userPlan.templateId?.title || 
								 userPlan.autoGeneratedPlanId ? "Auto-Generated Plan" : 
								 "Your Active Plan"}
							</h2>
							
							<div className="grid grid-cols-1 md:grid-cols-2 gap-4 mt-4">
								{(userPlan.templateId?.goal || userPlan.autoGeneratedPlanId?.generationParams?.goals?.[0]) && (
									<div className="stat bg-base-200 rounded-lg">
										<div className="stat-title">Goal</div>
										<div className="stat-value text-2xl capitalize">
											{userPlan.templateId?.goal || 
											 userPlan.autoGeneratedPlanId?.generationParams?.goals?.[0]?.replace("_", " ")}
										</div>
									</div>
								)}
								
								{(userPlan.templateId?.level || userPlan.autoGeneratedPlanId?.generationParams?.experience_level) && (
									<div className="stat bg-base-200 rounded-lg">
										<div className="stat-title">Level</div>
										<div className="stat-value text-2xl capitalize">
											{userPlan.templateId?.level || 
											 userPlan.autoGeneratedPlanId?.generationParams?.experience_level}
										</div>
									</div>
								)}
								
								{userPlan.currentWeek && (
									<div className="stat bg-base-200 rounded-lg">
										<div className="stat-title">Current Week</div>
										<div className="stat-value text-2xl">
											Week {userPlan.currentWeek}
											{(userPlan.templateId?.weeks || userPlan.autoGeneratedPlanId?.currentWeek) && 
											 ` / ${userPlan.templateId?.weeks || "∞"}`}
										</div>
									</div>
								)}
								
								{userPlan.currentDayIndex !== undefined && (
									<div className="stat bg-base-200 rounded-lg">
										<div className="stat-title">Current Day</div>
										<div className="stat-value text-2xl">
											Day {userPlan.currentDayIndex + 1}
											{(userPlan.templateId?.daysPerWeek || 
											  userPlan.autoGeneratedPlanId?.generationParams?.days_per_week) && 
											 ` / ${userPlan.templateId?.daysPerWeek || 
											       userPlan.autoGeneratedPlanId?.generationParams?.days_per_week}`}
										</div>
									</div>
								)}
							</div>

							{userPlan.startedAt && (
								<div className="mt-4">
									<p className="text-sm text-base-content/70">
										Started on: {new Date(userPlan.startedAt).toLocaleDateString()}
									</p>
								</div>
							)}

							<div className="card-actions justify-end mt-4">
								<button 
									className="btn btn-primary"
									onClick={() => window.location.href = '/dashboard'}
								>
									Go to Dashboard
								</button>
								{userPlan.autoGeneratedPlanId && (
									<button 
										className="btn btn-info"
										onClick={handleCheckProgression}
										disabled={loadingProgression}
									>
										{loadingProgression ? (
											<span className="loading loading-spinner loading-sm"></span>
										) : (
											<>
												<TrendingUp className="w-4 h-4 mr-2" />
												Check Progression
											</>
										)}
									</button>
								)}
							</div>
						</div>
					</div>

					{/* Workout Details Card */}
					{(userPlan.templateId?.dayTemplates?.length > 0 || 
					  userPlan.autoGeneratedPlanId?.weeklyStructure?.length > 0) && (
						<div className="card bg-base-100 shadow-lg">
							<div className="card-body">
								{renderWorkoutDays()}
							</div>
						</div>
					)}

					{/* Progression History - Show if available */}
					{renderProgressionHistory()}
				</div>
			) : (
				<div className="card bg-base-100 shadow-lg p-6">
					<p className="text-center text-base-content/70">
						Your active plans will appear here...
					</p>
				</div>
			)}
		</div>
	);
};

export default MyPlans;
