import { useEffect, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { Calendar, ArrowLeft, Play, Dumbbell, Clock, ChevronLeft, ChevronRight } from "lucide-react";
import { useDailySessionStore } from "../store/dailySession/dailySessionStore";
import { useStreakStore } from "../store/streak/streakStore";
import PageContainer from "../components/PageContainer";

const TodayWorkout = () => {
	const navigate = useNavigate();
	const { todaySession, isLoading, getTodaySession } = useDailySessionStore();
	const { streak, getStreak } = useStreakStore();
	const [showCalendar, setShowCalendar] = useState(false);
	const [upcomingWorkouts, setUpcomingWorkouts] = useState([]);

	useEffect(() => {
		getTodaySession();
		getStreak();
	}, []);

	useEffect(() => {
		if (todaySession) {
			generateUpcomingWorkouts();
		}
	}, [todaySession]);

	const generateUpcomingWorkouts = async () => {
		// Get user plan info from the session
		if (!todaySession) return;

		try {
			// Fetch user's plan to get preferred workout days
			const response = await fetch('/api/user-plan', {
				credentials: 'include'
			});
			
			if (!response.ok) {
				// Fallback to simple pattern
				generateSimplePattern();
				return;
			}

			const data = await response.json();
			const userPlan = data.userPlan;

			const workouts = [];
			const today = new Date();
			today.setHours(0, 0, 0, 0);

			// Get preferred days from plan
			let preferredDays = [];
			if (userPlan?.autoGeneratedPlanId?.generationParams?.preferred_days) {
				preferredDays = userPlan.autoGeneratedPlanId.generationParams.preferred_days;
			} else if (userPlan?.templateId?.preferredDays) {
				preferredDays = userPlan.templateId.preferredDays;
			}

			// Map day names to numbers
			const dayNameToNumber = {
				sunday: 0,
				monday: 1,
				tuesday: 2,
				wednesday: 3,
				thursday: 4,
				friday: 5,
				saturday: 6,
			};

			const preferredDayNumbers = preferredDays.map(day => 
				dayNameToNumber[day.toLowerCase()]
			);

			// Generate next 14 days
			for (let i = 0; i < 14; i++) {
				const date = new Date(today);
				date.setDate(date.getDate() + i);
				const dayOfWeek = date.getDay();

				if (preferredDayNumbers.includes(dayOfWeek)) {
					workouts.push({
						date: new Date(date),
						isToday: i === 0,
						exerciseCount: todaySession.exercises?.length || 0,
						completed: false,
						dayName: Object.keys(dayNameToNumber).find(
							key => dayNameToNumber[key] === dayOfWeek
						),
					});
				}
			}

			setUpcomingWorkouts(workouts);
		} catch (error) {
			console.error('Error fetching workout schedule:', error);
			generateSimplePattern();
		}
	};

	const generateSimplePattern = () => {
		const workouts = [];
		const today = new Date();
		today.setHours(0, 0, 0, 0);

		// Default pattern: Monday, Wednesday, Friday
		const defaultDays = [1, 3, 5]; // Monday, Wednesday, Friday

		for (let i = 0; i < 14; i++) {
			const date = new Date(today);
			date.setDate(date.getDate() + i);
			const dayOfWeek = date.getDay();

			if (defaultDays.includes(dayOfWeek) || i === 0) {
				workouts.push({
					date: new Date(date),
					isToday: i === 0,
					exerciseCount: todaySession?.exercises?.length || 0,
					completed: false,
				});
			}
		}

		setUpcomingWorkouts(workouts);
	};

	if (isLoading) {
		return (
			<PageContainer>
				<div className="flex justify-center items-center min-h-[400px]">
					<span className="loading loading-spinner loading-lg"></span>
				</div>
			</PageContainer>
		);
	}

	if (!todaySession) {
		return (
			<PageContainer>
				<div className="text-center py-12">
					<Calendar className="w-16 h-16 mx-auto text-base-content/30 mb-4" />
					<h2 className="text-2xl font-bold mb-2">
						No Workout Today
					</h2>
					<p className="text-base-content/70 mb-6">
						You don't have a workout scheduled for today.
					</p>
					<Link to="/plans" className="btn btn-primary">
						Browse Plans
					</Link>
				</div>
			</PageContainer>
		);
	}

	return (
		<PageContainer>
			<div className="flex flex-col gap-6">
				{/* Header with Streak */}
				<div className="flex items-center justify-between">
					<div>
						<h1 className="text-3xl font-bold">Today's Workout</h1>
						<p className="text-base-content/70">
							{new Date().toLocaleDateString("en-US", {
								weekday: "long",
								year: "numeric",
								month: "long",
								day: "numeric",
							})}
						</p>
						{streak && (
							<div className="flex items-center gap-2 mt-2">
								<span className="badge badge-primary badge-lg">
									🔥 {streak.currentStreak} day streak
								</span>
								<span className="text-sm opacity-70">
									• {streak.totalWorkouts} total workouts
								</span>
							</div>
						)}
					</div>
					<Link
						to="/workout-calendar"
						className="btn btn-outline gap-2"
					>
						<Calendar className="w-4 h-4" />
						View Calendar
					</Link>
				</div>

				{/* Start Workout Button */}
				<div className="card bg-linear-to-r from-primary to-secondary text-primary-content shadow-xl">
					<div className="card-body">
						<div className="flex items-center justify-between">
							<div>
								<h2 className="card-title text-2xl mb-2">
									Ready to crush it?
								</h2>
								<p className="opacity-90">
									{todaySession.exercises?.length || 0}{" "}
									exercises waiting for you
								</p>
							</div>
							<button
								onClick={() => navigate("/workout-session")}
								className="btn btn-lg btn-accent gap-2"
							>
								<Play className="w-5 h-5" />
								Start Workout
							</button>
						</div>
					</div>
				</div>

				{/* Calendar Toggle Button */}
				<div className="flex justify-center">
					<button
						onClick={() => setShowCalendar(!showCalendar)}
						className="btn btn-outline btn-sm gap-2"
					>
						<Calendar className="w-4 h-4" />
						{showCalendar ? 'Hide Schedule' : 'View 2-Week Schedule'}
					</button>
				</div>

				{/* Upcoming Workouts Calendar */}
				{showCalendar && (
					<div className="card bg-base-200 shadow-xl">
						<div className="card-body">
							<h3 className="card-title text-lg flex items-center gap-2">
								<Calendar className="w-5 h-5" />
								Upcoming Workout Schedule
							</h3>
							<div className="grid grid-cols-7 gap-2 mt-4">
								{/* Day headers */}
								{['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'].map((day) => (
									<div
										key={day}
										className="text-center text-xs font-semibold text-base-content/70 p-2"
									>
										{day}
									</div>
								))}

								{/* Generate calendar grid for 2 weeks */}
								{Array.from({ length: 14 }).map((_, i) => {
									const date = new Date();
									date.setDate(date.getDate() + i);
									
									const workout = upcomingWorkouts.find(
										(w) =>
											w.date.getDate() === date.getDate() &&
											w.date.getMonth() === date.getMonth()
									);

									const isToday = i === 0;

									return (
										<div
											key={i}
											className={`
												relative p-2 rounded-lg text-center transition-all
												${workout ? 'bg-primary/20 border-2 border-primary' : 'bg-base-300'}
												${isToday ? 'ring-2 ring-accent' : ''}
												${workout ? 'hover:bg-primary/30 cursor-pointer' : ''}
											`}
											title={
												workout
													? `Workout Day - ${workout.exerciseCount} exercises`
													: 'Rest Day'
											}
										>
											<div className="text-xs font-semibold">
												{date.getDate()}
											</div>
											{isToday && (
												<div className="text-[10px] font-bold text-accent mt-1">
													TODAY
												</div>
											)}
											{workout && (
												<div className="mt-1">
													<Dumbbell className="w-3 h-3 mx-auto text-primary" />
												</div>
											)}
											{workout?.completed && (
												<div className="absolute top-0 right-0 w-2 h-2 bg-success rounded-full" />
											)}
										</div>
									);
								})}
							</div>

							{/* Legend */}
							<div className="flex flex-wrap gap-3 mt-4 text-xs">
								<div className="flex items-center gap-1">
									<div className="w-4 h-4 rounded bg-primary/20 border-2 border-primary" />
									<span>Workout Day</span>
								</div>
								<div className="flex items-center gap-1">
									<div className="w-4 h-4 rounded bg-base-300" />
									<span>Rest Day</span>
								</div>
								<div className="flex items-center gap-1">
									<div className="w-4 h-4 rounded ring-2 ring-accent" />
									<span>Today</span>
								</div>
							</div>
						</div>
					</div>
				)}

				{/* Exercises List */}
				<div className="card bg-base-100 shadow-lg">
					<div className="card-body">
						<div className="flex items-center justify-between mb-4">
							<h2 className="card-title">Today's Exercises</h2>
							<Link
								to="/workout-history"
								className="btn btn-ghost btn-sm gap-2"
							>
								View History
							</Link>
						</div>
						<div className="space-y-4">
							{todaySession.exercises?.map((exercise, index) => (
								<div
									key={index}
									className="p-4 bg-base-200 rounded-lg hover:bg-base-300 transition-colors"
								>
									<div className="flex items-start gap-3">
										<div className="badge badge-primary badge-lg">
											{index + 1}
										</div>
										<div className="flex-1">
											<h3 className="font-semibold text-lg flex items-center gap-2 mb-2">
												<Dumbbell className="w-5 h-5" />
												{exercise.exerciseId?.name ||
													"Exercise"}
											</h3>
											
											{/* Exercise Description */}
											{exercise.exerciseId?.description && (
												<p className="text-sm text-base-content/70 mb-3">
													{exercise.exerciseId.description}
												</p>
											)}

											{/* Muscles Targeted */}
											{exercise.exerciseId?.primary_muscles && (
												<div className="mb-3">
													<p className="text-xs font-semibold text-base-content/60 mb-1">
														TARGET MUSCLES:
													</p>
													<div className="flex flex-wrap gap-1">
														{exercise.exerciseId.primary_muscles.map((muscle, i) => (
															<span
																key={i}
																className="badge badge-sm badge-outline"
															>
																{muscle}
															</span>
														))}
														{exercise.exerciseId.secondary_muscles?.map((muscle, i) => (
															<span
																key={`sec-${i}`}
																className="badge badge-sm badge-ghost"
															>
																{muscle}
															</span>
														))}
													</div>
												</div>
											)}

											{/* Workout Plan */}
											{exercise.planned && (
												<div className="mb-2">
													<p className="text-xs font-semibold text-base-content/60 mb-1">
														WORKOUT PLAN:
													</p>
													<div className="flex flex-wrap gap-2 text-sm">
														{exercise.planned.sets && (
															<span className="badge badge-primary">
																{exercise.planned.sets} sets
															</span>
														)}
														{exercise.planned.reps && (
															<span className="badge badge-secondary">
																{exercise.planned.reps} reps
															</span>
														)}
														{exercise.planned.load_kg && (
															<span className="badge badge-accent">
																{exercise.planned.load_kg} kg
															</span>
														)}
														{exercise.planned.time_seconds && (
															<span className="badge badge-info">
																<Clock className="w-3 h-3 mr-1" />
																{exercise.planned.time_seconds}s
															</span>
														)}
														{exercise.planned.rest_seconds && (
															<span className="badge badge-ghost">
																Rest: {exercise.planned.rest_seconds}s
															</span>
														)}
													</div>
												</div>
											)}

											{/* Equipment */}
											{exercise.exerciseId?.equipment && 
											 exercise.exerciseId.equipment.length > 0 && (
												<div className="mb-2">
													<p className="text-xs font-semibold text-base-content/60 mb-1">
														EQUIPMENT:
													</p>
													<div className="flex flex-wrap gap-1">
														{exercise.exerciseId.equipment.map((equip, i) => (
															<span
																key={i}
																className="badge badge-xs badge-neutral"
															>
																{equip}
															</span>
														))}
													</div>
												</div>
											)}

											{/* Cue/Tips */}
											{exercise.cue && (
												<div className="alert alert-info py-2 mt-3">
													<svg
														xmlns="http://www.w3.org/2000/svg"
														fill="none"
														viewBox="0 0 24 24"
														className="stroke-current shrink-0 w-4 h-4"
													>
														<path
															strokeLinecap="round"
															strokeLinejoin="round"
															strokeWidth="2"
															d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
														></path>
													</svg>
													<span className="text-sm">
														💡 {exercise.cue}
													</span>
												</div>
											)}

											{/* Difficulty Badge */}
											{exercise.exerciseId?.difficulty && (
												<div className="mt-2">
													<span className={`badge badge-sm ${
														exercise.exerciseId.difficulty === 'beginner' 
															? 'badge-success' 
															: exercise.exerciseId.difficulty === 'intermediate'
															? 'badge-warning'
															: 'badge-error'
													}`}>
														{exercise.exerciseId.difficulty}
													</span>
												</div>
											)}
										</div>
									</div>
								</div>
							))}
						</div>
					</div>
				</div>
			</div>
		</PageContainer>
	);
};

export default TodayWorkout;
