import mongoose from "mongoose";
import PrescriptionSchema from "./prescription.model.js";
const { Schema } = mongoose;

const GenerationParamsSchema = new Schema(
	{
		goals: { type: [String], default: [] },
		experience_level: {
			type: String,
			enum: ["beginner", "intermediate", "advanced"],
			default: "beginner",
		},
		equipment: { type: [String], default: [] },
		days_per_week: { type: Number, min: 2, max: 6, default: 3 },
		session_length_minutes: { type: Number, default: 45 },
		injuries: { type: [String], default: [] },
		focus_areas: { type: [String], default: [] },
	},
	{ _id: false }
);

const ProgressionRuleSchema = new Schema(
	{
		method: {
			type: String,
			enum: ["reps", "load", "reps_then_load", "time"],
			default: "reps_then_load",
		},
		trigger: { type: String, default: "complete_all_sets_twice" },
	},
	{ _id: false }
);

const WeeklyExerciseSchema = new Schema(
	{
		exerciseId: {
			type: Schema.Types.ObjectId,
			ref: "Exercise",
			required: true,
		},
		planned: { type: PrescriptionSchema, default: () => ({}) },
		variant: {
			type: String,
			enum: ["base", "advanced", "easier"],
			default: "base",
		},
		cue: { type: String, default: "" },
		progression_rule: { type: ProgressionRuleSchema, default: () => ({}) },
	},
	{ _id: false }
);

const WeeklyStructureSchema = new Schema(
	{
		dayNumber: { type: Number, required: true, min: 1, max: 7 },
		name: { type: String, default: "" },
		focus: { type: String, default: "" },
		exercises: { type: [WeeklyExerciseSchema], default: [] },
	},
	{ _id: false }
);

const AdjustmentSchema = new Schema(
	{
		exerciseId: { type: Schema.Types.ObjectId, ref: "Exercise" },
		change: { type: String, default: "" },
		reason: { type: String, default: "" },
	},
	{ _id: false }
);

const ProgressionHistorySchema = new Schema(
	{
		date: { type: String, required: true },
		adjustments: { type: [AdjustmentSchema], default: [] },
	},
	{ _id: false }
);

const AutoGeneratedPlanSchema = new Schema(
	{
		userId: { type: Schema.Types.ObjectId, ref: "User", required: true },
		planType: { type: String, default: "auto_generated" },
		generationParams: {
			type: GenerationParamsSchema,
			default: () => ({}),
		},
		weeklyStructure: { type: [WeeklyStructureSchema], default: [] },
		currentWeek: { type: Number, default: 1 },
		progressionHistory: { type: [ProgressionHistorySchema], default: [] },
		startedAt: { type: Date, default: Date.now },
		lastModified: { type: Date, default: Date.now },
		active: { type: Boolean, default: true },
	},
	{ timestamps: true }
);

AutoGeneratedPlanSchema.index({ userId: 1, active: 1 });

const AutoGeneratedPlan =
	mongoose.models.AutoGeneratedPlan ||
	mongoose.model("AutoGeneratedPlan", AutoGeneratedPlanSchema);
export default AutoGeneratedPlan;
